---
title: "List of Recodes"
author: "Simon J. Kiss"
date: '2022-07-24'
output: html_document
---

# Introduction 

This document describes what has been done to the original variables produced for the 2022 Ontario Provincial Election Study

# Party names
This variable uses Q6b to simplify party names and shorten them. These are:
- PC
- Liberal
- NDP
- Green

## Variables Q31_, Q32,

Q31_: Qualtrics categorized responses from 1 to 11, which were transformed to 0-10 by subtracting 1 from each value.
Q32_: Qualtrics categorized responses from 1 to 12, with 12 being the "Don't Know" responses. The data was transformed to a 0-11 scale before shifting the 11 (DK values) to be added to the bin of "5" values. The new variables were output with a "_x" at the end.
Q33a_: Qualtrics categorized responses from 1 to 12, with 12 being the "Don't Know" responses. The data was transformed to a 0-11 scale before shifting the 11 (DK values) to be added to the bin of "5" values. The new variables were output with a "_x" at the end.
Q80_: Qualtrics categorized responses from 1 to 12, with 12 being the "Don't Know" responses. The data was transformed to a 0-11 scale before shifting the 11 (DK values) to be added to the bin of "5" values. The new variables were output with a "_x" at the end.

## Variables ending with _x

These variables are transformed versions of the same variable without the suffix `_x`. These variables have been transformed: 

1. Don't know response were set to a middle category, to increase sample size
2. Rescaled from 0 to 1. 

## Vote Variable

## Renter Vote Variable

## Housing Status

Respondents were divided into 5 groups:
-Speculator (Landlords who plan to stay where they are)
-First-Time homebuyer (Renters who plan to purchase a new home or condominium)
-Satisfied renter (Renters who plan to stay where they are)
-Satisfied owner (Owners who plan to stay where they are)
-Other (everyone else)

## Swing Variable

## Abstain Variable

## Partisanship
This variable has been constructed from Q23 which asks whether a person identifies with an Ontario provincial party and Q24, how strongly they identify with that. 
If they satisfy the conditions, they are labeled as a partisan. Categories are: 
- PC
- Liberal
- NDP
- Green
- Independent


## Experimental Group Variable
This variable describe which experimental treatment the respondent was exposed to. Values include: 

- Control
- Social
- Private
- Public

The full text of the treatment is available in the data dictariony. This value was taken from the dichotomous variables Q35_1_exp through Q35_4_exp. 

